UPDATE propiedades
SET estado = CASE UPPER(TRIM(estado))
  WHEN 'PRELIMINAR' THEN 'BORRADOR'
  WHEN 'EN_VALIDACION' THEN 'BORRADOR'
  WHEN 'DESCARTADA' THEN 'ARCHIVADA'
  WHEN 'INACTIVA' THEN 'ARCHIVADA'
  ELSE UPPER(TRIM(estado))
END
WHERE UPPER(TRIM(estado)) IN (
  'PRELIMINAR',
  'EN_VALIDACION',
  'DESCARTADA',
  'INACTIVA',
  'BORRADOR',
  'DISPONIBLE',
  'RESERVADA',
  'VENDIDA',
  'ARCHIVADA'
);
