[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "./coverage"

# Threshold de cobertura del 80% (líneas, funciones, sentencias)
coverageThreshold = 0.99

coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/*.spec.ts",
  "**/*.test.ts",
  "src/utils/**",
  "*.config.js",
  "generated/**"
]
