global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'cloudflare'
    scrape_interval: 60s
    scrape_timeout: 30s
    static_configs:
      - targets: ['cloudflare-prometheus-exporter.adeityssx.workers.dev']
