apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alvas-api
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - alvas
  selector:
    matchLabels:
      app: alvas-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
