-- Limpieza de BD local vía rollback de migraciones (más limpio que DELETE)
-- Ejecutar desde apps/api/:
--   wrangler d1 migrations apply alvas-dev --local -t 0
--   wrangler d1 migrations apply alvas-dev --local
--
-- Equivalente SQL manual (solo si no funciona rollback):
-- DROP TABLE IF EXISTS ventas_actividad;
-- DROP TABLE IF EXISTS ventas_citas;
-- DROP TABLE IF EXISTS ventas_clientes;
-- DROP TABLE IF EXISTS ventas_contratos;
-- DROP TABLE IF EXISTS ventas_leads;
-- DROP TABLE IF EXISTS propiedades;
-- DROP TABLE IF EXISTS integraciones_captaciones_pendientes;
-- DROP TABLE IF EXISTS usuarios;
